namespace Maliev.OrderService.Domain.Entities;

/// <summary>
/// Represents a preview image for a part side (FRONT, LEFT, RIGHT, BACK, TOP, BOTTOM).
/// Generated by GeometryService when a 3D file is analyzed.
/// </summary>
public class OrderPreviewImage
{
    /// <summary>Gets or sets the preview image identifier.</summary>
    public long PreviewImageId { get; set; }

    /// <summary>Gets or sets the order identifier.</summary>
    public string OrderId { get; set; } = null!;

    /// <summary>Gets or sets the side name (Front, Left, Right, Back, Top, Bottom).</summary>
    public string Side { get; set; } = null!;

    /// <summary>Gets or sets the GCS storage path.</summary>
    public string StoragePath { get; set; } = null!;

    /// <summary>Gets or sets when the preview was generated.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Gets or sets the source file identifier (which 3D file generated this preview).</summary>
    public long? SourceFileId { get; set; }

    // Navigation Properties
    /// <summary>Gets or sets the parent order navigation property.</summary>
    public Order Order { get; set; } = null!;

    /// <summary>Gets or sets the source file navigation property.</summary>
    public OrderFile? SourceFile { get; set; }
}
