// <auto-generated />
using System;
using Maliev.OrderService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260620010153_AddOrderQuoteVersionReference")]
    partial class AddOrderQuoteVersionReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_id_seq");

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ChangeDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("change_details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("performed_by");

                    b.HasKey("AuditId")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix__audit_log__action");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix__audit_log__order_id");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("ix__audit_log__performed_at");

                    b.HasIndex("PerformedBy")
                        .HasDatabaseName("ix__audit_log__performed_by");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.NotificationSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("Channels")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("channels");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_subscribed");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SubscriptionId")
                        .HasName("pk_notification_subscriptions");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix__notification_subscription__customer_id");

                    b.ToTable("notification_subscriptions", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_delivery_date");

                    b.Property<string>("AssignedEmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_employee_id");

                    b.Property<Guid?>("BillingAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_address_id");

                    b.Property<string>("BillingCompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("billing_company_name");

                    b.Property<string>("BillingVatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("billing_vat_number");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer")
                        .HasColumnName("color_id");

                    b.Property<string>("ColorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("CustomerPoFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_po_file_id");

                    b.Property<string>("CustomerPoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_po_number");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_type");

                    b.Property<string>("DeliveryContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_contact_email");

                    b.Property<string>("DeliveryContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_contact_name");

                    b.Property<string>("DeliveryContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("delivery_contact_phone");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsConfidential")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_confidential");

                    b.Property<bool>("IsOutsourced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_outsourced");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<int?>("ManufacturedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("manufactured_quantity");

                    b.Property<DateTime?>("MaterialCacheUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("material_cache_updated_at");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_name");

                    b.Property<int?>("OrderedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_quantity");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("payment_status");

                    b.Property<int?>("ProcessTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("process_type_id");

                    b.Property<string>("ProductionItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("production_items_json");

                    b.Property<DateTime?>("PromisedDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promised_delivery_date");

                    b.Property<string>("QuoteCurrency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("THB")
                        .HasColumnName("quote_currency");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("QuoteNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("quote_number");

                    b.Property<Guid?>("QuoteVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_version_id");

                    b.Property<int?>("QuoteVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("quote_version_number");

                    b.Property<decimal?>("QuotedAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quoted_amount");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.Property<Guid?>("ShippingAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipping_address_id");

                    b.Property<string>("ShippingAddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("shipping_address_line1");

                    b.Property<string>("ShippingAddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("shipping_address_line2");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shipping_city");

                    b.Property<string>("ShippingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shipping_country");

                    b.Property<string>("ShippingPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shipping_postal_code");

                    b.Property<string>("ShippingProvince")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shipping_province");

                    b.Property<decimal?>("SupplierCostTHB")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("supplier_cost_thb");

                    b.Property<DateTime?>("SupplierEstimatedDelivery")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("supplier_estimated_delivery");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supplier_name");

                    b.Property<int?>("SurfaceFinishingId")
                        .HasColumnType("integer")
                        .HasColumnName("surface_finishing_id");

                    b.Property<string>("SurfaceFinishingName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surface_finishing_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrderId")
                        .HasName("pk_orders");

                    b.HasIndex("AssignedEmployeeId")
                        .HasDatabaseName("ix__order__assigned_employee_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix__order__created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix__order__customer_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix__order__department_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix__order__material_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix__order__payment_id");

                    b.HasIndex("ProcessTypeId")
                        .HasDatabaseName("ix__order__process_type_id");

                    b.HasIndex("ServiceCategoryId")
                        .HasDatabaseName("ix_orders_service_category_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order3DDesignAttributes", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("ComplexityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("complexity_level");

                    b.Property<string>("Deliverables")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deliverables");

                    b.Property<string>("DesignSoftware")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("design_software");

                    b.Property<int>("RevisionRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("revision_rounds");

                    b.HasKey("OrderId")
                        .HasName("pk_order_3d_design_attributes");

                    b.ToTable("order_3d_design_attributes", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order3DPrintingAttributes", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<bool>("InsertRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("insert_required");

                    b.Property<bool>("PartAssemblyTestRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("part_assembly_test_required");

                    b.Property<string>("PartMarking")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_marking");

                    b.Property<bool>("ThreadTapRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("thread_tap_required");

                    b.HasKey("OrderId")
                        .HasName("pk_order_3d_printing_attributes");

                    b.ToTable("order_3d_printing_attributes", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order3DScanningAttributes", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<bool>("DeviationReportRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deviation_report_requested");

                    b.Property<string>("OutputFileFormats")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("output_file_formats");

                    b.Property<string>("RequiredAccuracy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("required_accuracy");

                    b.Property<string>("ScanLocation")
                        .HasColumnType("text")
                        .HasColumnName("scan_location");

                    b.HasKey("OrderId")
                        .HasName("pk_order_3d_scanning_attributes");

                    b.ToTable("order_3d_scanning_attributes", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderCncMachiningAttributes", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("InspectionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inspection_type");

                    b.Property<string>("SurfaceRoughness")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("surface_roughness");

                    b.Property<bool>("TapRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tap_required");

                    b.Property<string>("Tolerance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tolerance");

                    b.HasKey("OrderId")
                        .HasName("pk_order_cnc_machining_attributes");

                    b.HasIndex("Tolerance")
                        .HasDatabaseName("ix__order_cnc_machining_attributes__tolerance");

                    b.ToTable("order_cnc_machining_attributes", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderFile", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FileId"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Internal")
                        .HasColumnName("access_level");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DesignUnits")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("design_units");

                    b.Property<string>("FileCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_category");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_role");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("ObjectPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_path");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("FileId")
                        .HasName("pk_order_files");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix__order_file__deleted_at");

                    b.HasIndex("FileCategory")
                        .HasDatabaseName("ix__order_file__file_category");

                    b.HasIndex("FileRole")
                        .HasDatabaseName("ix__order_file__file_role");

                    b.HasIndex("ObjectPath")
                        .IsUnique()
                        .HasDatabaseName("ix__order_file__object_path");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix__order_file__order_id");

                    b.ToTable("order_files", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderNote", b =>
                {
                    b.Property<long>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("note_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_text");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("note_type");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.HasKey("NoteId")
                        .HasName("pk_order_notes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix__order_note__created_at");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix__order_note__created_by");

                    b.HasIndex("NoteType")
                        .HasDatabaseName("ix__order_note__note_type");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix__order_note__order_id");

                    b.ToTable("order_notes", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderPreviewImage", b =>
                {
                    b.Property<long>("PreviewImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("preview_image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PreviewImageId"));

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("side");

                    b.Property<long?>("SourceFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_file_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.HasKey("PreviewImageId")
                        .HasName("pk_order_preview_images");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix__order_preview_image__order_id");

                    b.HasIndex("Side")
                        .HasDatabaseName("ix__order_preview_image__side");

                    b.HasIndex("SourceFileId")
                        .HasDatabaseName("ix_order_preview_images_source_file_id");

                    b.HasIndex("OrderId", "Side")
                        .IsUnique()
                        .HasDatabaseName("ix__order_preview_image__order_id__side");

                    b.ToTable("order_preview_images", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderSheetMetalAttributes", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("InspectionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inspection_type");

                    b.Property<string>("Thickness")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("thickness");

                    b.Property<string>("Tolerance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tolerance");

                    b.Property<string>("WeldingDetails")
                        .HasColumnType("text")
                        .HasColumnName("welding_details");

                    b.Property<bool>("WeldingRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("welding_required");

                    b.HasKey("OrderId")
                        .HasName("pk_order_sheet_metal_attributes");

                    b.ToTable("order_sheet_metal_attributes", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<long>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StatusId"));

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text")
                        .HasColumnName("customer_notes");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text")
                        .HasColumnName("internal_notes");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("StatusId")
                        .HasName("pk_order_statuses");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix__order_status__order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix__order_status__status");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix__order_status__timestamp");

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.ProcessType", b =>
                {
                    b.Property<int>("ProcessTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("process_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProcessTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.HasKey("ProcessTypeId")
                        .HasName("pk_process_types");

                    b.HasIndex("ServiceCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix__process_type__service_category_id__name");

                    b.ToTable("process_types", (string)null);
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_service_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix__service_category__name");

                    b.ToTable("service_categories", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_~");

                    b.ToTable("outbox_message");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithMany("AuditLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.ProcessType", "ProcessType")
                        .WithMany("Orders")
                        .HasForeignKey("ProcessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_process_types_process_type_id");

                    b.HasOne("Maliev.OrderService.Domain.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_service_categories_service_category_id");

                    b.Navigation("ProcessType");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order3DDesignAttributes", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithOne("DesignAttributes")
                        .HasForeignKey("Maliev.OrderService.Domain.Entities.Order3DDesignAttributes", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_3d_design_attributes_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order3DPrintingAttributes", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithOne("PrintingAttributes")
                        .HasForeignKey("Maliev.OrderService.Domain.Entities.Order3DPrintingAttributes", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_3d_printing_attributes_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order3DScanningAttributes", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithOne("ScanningAttributes")
                        .HasForeignKey("Maliev.OrderService.Domain.Entities.Order3DScanningAttributes", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_3d_scanning_attributes_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderCncMachiningAttributes", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithOne("CncAttributes")
                        .HasForeignKey("Maliev.OrderService.Domain.Entities.OrderCncMachiningAttributes", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_cnc_machining_attributes_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderFile", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithMany("OrderFiles")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_files_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderNote", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithMany("OrderNotes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_notes_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderPreviewImage", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_preview_images_orders_order_id");

                    b.HasOne("Maliev.OrderService.Domain.Entities.OrderFile", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .HasConstraintName("fk_order_preview_images_order_files_source_file_id");

                    b.Navigation("Order");

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderSheetMetalAttributes", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithOne("SheetMetalAttributes")
                        .HasForeignKey("Maliev.OrderService.Domain.Entities.OrderSheetMetalAttributes", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_sheet_metal_attributes_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.OrderStatus", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.Order", "Order")
                        .WithMany("OrderStatuses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_statuses_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.ProcessType", b =>
                {
                    b.HasOne("Maliev.OrderService.Domain.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("ProcessTypes")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_types_service_categories_service_category_id");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message__outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_~");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.Order", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CncAttributes");

                    b.Navigation("DesignAttributes");

                    b.Navigation("OrderFiles");

                    b.Navigation("OrderNotes");

                    b.Navigation("OrderStatuses");

                    b.Navigation("PrintingAttributes");

                    b.Navigation("ScanningAttributes");

                    b.Navigation("SheetMetalAttributes");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.ProcessType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Maliev.OrderService.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProcessTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
