name: Validate - Develop

on:
  push:
    branches: [develop]

permissions:
  contents: read

concurrency:
  group: order-validate-develop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
